coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50%
        base: auto
    patch:
      default:
        target: auto
        threshold: 50%
        base: auto
