version: 1
disable_existing_loggers: true
formatters:
  user:
    format: '%(asctime)s %(levelname)s :: %(message)s'
    datefmt: '%m/%d/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: user
    stream: 'ext://sys.stdout'
root:
  level: INFO
  handlers:
    - console
