name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: Install TA-Lib
        run: |
          wget https://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar xvfz ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure
          make
          sudo make install
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --no-deps -r requirements-no-deps.txt
      - name: Run tests and collect coverage
        run: python3 -m pytest --cov=afang/ --cov=user_strategies/ tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
