name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov=afang tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
